@Bookstore.Web_HostAddress = https://localhost:7074

GET {{Bookstore.Web_HostAddress}}/books/
Accept: application/json

###

@BookID=a29b0d03-75bd-4590-a0c6-bec4bcc2908e
GET {{Bookstore.Web_HostAddress}}/books/{{BookID}}
Accept: application/json

###

POST {{Bookstore.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "b29b0d03-75bd-4590-a0c6-bec4bcc2908e",
  "title": "Modular Monoliths",
  "author": "Steve Smith",
  "price": 19.99
}

###

@BookID=b29b0d03-75bd-4590-a0c6-bec4bcc2908e
DELETE {{Bookstore.Web_HostAddress}}/books/{{BookID}}
Accept: application/json

###

POST {{Bookstore.Web_HostAddress}}/books/b29b0d03-75bd-4590-a0c6-bec4bcc2908e/price-history
Accept: application/json
Content-Type: application/json

{
  "id": "b29b0d03-75bd-4590-a0c6-bec4bcc2908e",
  "price": 1.99
}

###

POST {{Bookstore.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "petar@test.com",
  "password": "Pa$$word1"
}

###


POST {{Bookstore.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "petar@test.com",
  "password": "Pa$$word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJwZXRhckB0ZXN0LmNvbSIsImlhdCI6MTcxNzA4NzMwMSwiZXhwIjoxNzE3MDkwOTAxLCJuYmYiOjE3MTcwODczMDF9.3cSjqwg-ZOk-5sAav3SZFRSRvQMNROSwV7pRoIfD52E