@Bookstore.Web_HostAddress = https://localhost:7074

GET {{Bookstore.Web_HostAddress}}/books/
Accept: application/json

###

GET {{Bookstore.Web_HostAddress}}/books/a29b0d03-75bd-4590-a0c6-bec4bcc2908e
Accept: application/json

###

POST {{Bookstore.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "b29b0d03-75bd-4590-a0c6-bec4bcc2908e",
  "title": "Modular Monoliths",
  "author": "Steve Smith",
  "price": 19.99
}

###

DELETE {{Bookstore.Web_HostAddress}}/books/b29b0d03-75bd-4590-a0c6-bec4bcc2908e
Accept: application/json

###

POST {{Bookstore.Web_HostAddress}}/books/b29b0d03-75bd-4590-a0c6-bec4bcc2908e/price-history
Accept: application/json
Content-Type: application/json

{
  "id": "b29b0d03-75bd-4590-a0c6-bec4bcc2908e",
  "price": 1.99
}

###

# Create user

POST {{Bookstore.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "petar8@test.com",
  "password": "Pa$$word1"
}

###

# Login user

POST {{Bookstore.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "petar2@test.com",
  "password": "Pa$$word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJwZXRhcjJAdGVzdC5jb20iLCJpYXQiOjE3MTg0MzM2MTUsImV4cCI6MTcxODQzNzIxNSwibmJmIjoxNzE4NDMzNjE1fQ.csJ2TvBVPWxSK9JYUBPAS952amVtbEPQAMwdkVWpZbk

# Add item to cart
POST {{Bookstore.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookId": "b29b0d03-75bd-4590-a0c6-bec4bcc2908e",
  "quantity": 5
}

###

# List items in cart
GET {{Bookstore.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

# List All Orders
GET {{Bookstore.Web_HostAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###

# Checkout Cart
POST {{Bookstore.Web_HostAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "shippingAddressId":"576a3ca3-d5d9-4acb-84ba-136402a8ce74",
  "billingAddressId":"576a3ca3-d5d9-4acb-84ba-136402a8ce74"
}

###

# List Addresses
GET {{Bookstore.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

###

# Add address to user
POST {{Bookstore.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street1":"Test 4",
  "street2":"br. 2",
  "city":"Skopje",
  "state":"MK",
  "postalCode":"1000",
  "country":"Macedonia"
}

###

# Flush redis cache
POST {{Bookstore.Web_HostAddress}}/flush-cache
Accept: application/json
Content-Type: application/json

{
}

### 

# List emails
GET {{Bookstore.Web_HostAddress}}/emails
Accept: application/json
Authorization: Bearer {{token}}

### 

# Top Sales - Reach in reporting
GET {{Bookstore.Web_HostAddress}}/topsales?month=6&year=2024
Accept: application/json
//Authorization: Bearer {{token}}

###

# Top Sales 2 - Event ingeastion custom db
GET {{Bookstore.Web_HostAddress}}/topsales2?month=6&year=2024
Accept: application/json
//Authorization: Bearer {{token}}

### 